jasypt:
  encryptor:
    bean: jasyptEncryptorAES

spring:
#  datasource:
#    url: jdbc:h2:tcp://localhost/~/make-my-image
#    username: sa
#    password:
#    driver-class-name: org.h2.Driver
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ENC(VMZoTdq16Yb3s11/efWDXOEEkgjol2u1HJFe/2yfybjIpI98x99Lj5C04yil3RIUfyCOpnadXwjOw2pg0o77TdUyzQhL4KPOc6+HexQ04Gmg+vXTwljwxrHDXkLolYfs3khqhUXQq+rXBnYJg2OrTjhm/L1vKIkAyc3sKG0CkH86hVXym164kRI0KW7mYmhnrsPyMzlQb4+/53jS6pdbTxKL6Dvh5FlVxlHizPzUmJJmw9lDUiMc3Cw8i1gfCJzdkI3/qyQFVSaWFMWGEwGbcw==)
    username: ENC(8FonuGOAV7l2KOqdFr0G/TZ2WW2iWH226DjHeWEUAxbI014OiaEzu43yq5IoLXuA)
    password: ENC(+Wr1ag1u4Omy7xNYQpvS4dlr6QN8hueHmnZwB+axYojifDVu9LXqFVzPKDHuS3j1)

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        #        show_sql: true
        format_sql: true

logging:
  level:
    org.hibernate.sql: debug
    org.hibernate.type: trace